[project]
name = "researchgate-hub"
version = "0.1.0"
description = "TBA"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "zstandard>=0.25.0",
]
